version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: manga-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mangawebsite
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - manga-network

  # Next.js Application
  app:
    build: .
    container_name: manga-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/mangawebsite?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    volumes:
      - ./public/manga-images:/app/public/manga-images
      - ./public/manga-covers:/app/public/manga-covers
    depends_on:
      - mongo
    networks:
      - manga-network

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: manga-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - manga-network

volumes:
  mongo_data:

networks:
  manga-network:
    driver: bridge