import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots[object Object]
const baseUrl = 'https://mangareader.com';

return {
    rules: [object Object]
        userAgent: * ',
        allow: /   /series',
    /manga/ * ',
        / about',
    /contact',
        / guidelines',
    /privacy',
        / help,       / faq',
        ],
disallow: [
   /admin*,
    / api/*',
  /login',
   /signup',
    /profile',
     /settings',
   /upload',
          /creator-panel',
    /_next/*',
     /static/*',
   /*.json',
         /*.xml',
        ],
      },
  [object Object]
        userAgent: 'Googlebot',
        allow:   /   /series',
    /manga/*',
  /about',
    /contact',
       /guidelines',
    /privacy',
          /help,       /faq',
        ],
        disallow: [
   /admin*,
  /api/*',
  /login',
   /signup',
    /profile',
     /settings',
   /upload',
          /creator-panel',
    /_next/*',
     /static/*',
   /*.json',
         /*.xml',
        ],
        crawlDelay:1
      },
  [object Object]
        userAgent: Bingbot',
        allow:   /   /series',
    /manga/*',
  /about',
    /contact',
       /guidelines',
    /privacy',
          /help,       /faq',
        ],
        disallow: [
   /admin*,
  /api/*',
  /login',
   /signup',
    /profile',
     /settings',
   /upload',
          /creator-panel',
    /_next/*',
     /static/*',
   /*.json',
         /*.xml',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
} 