import { NextRequest, NextResponse } from 'next/server';
import { requireAuth, requireCreator } from '@/lib/auth';
import { subtitleGenerationAI } from '@/lib/ai-subtitle-generation';
import clientPromise from '@/lib/mongodb';
import { ObjectId } from 'mongodb';

// Generate subtitles for an episode
export async function POST(request: NextRequest) {
    try {
        const user = await requireAuth(request);
        const body = await request.json();

        const { episodeId, videoUrl, language, languageCode } = body;

        if (!episodeId || !videoUrl) {
            return NextResponse.json(
                { error: 'Episode ID and video URL are required' },
                { status: 400 }
            );
        }

        // Verify user has permission (creator of the series or admin)
        const client = await clientPromise;
        const db = client.db('mangawebsite');

        const episode = await db.collection('anime_episodes').findOne({
            _id: new ObjectId(episodeId)
        });

        if (!episode) {
            return NextResponse.json(
                { error: 'Episode not found' },
                { status: 404 }
            );
        }

        const series = await db.collection('anime_series').findOne({
            _id: new ObjectId(episode.seriesId)
        });

        if (!series) {
            return NextResponse.json(
                { error: 'Series not found' },
                { status: 404 }
            );
        }

        // Check permissions
        if (user.role !== 'admin' && series.creatorId !== user._id.toString()) {
            return NextResponse.json(
                { error: 'Forbidden - You do not have permission to generate subtitles for this episode' },
                { status: 403 }
            );
        }

        // Generate subtitles
        const subtitleTrack = await subtitleGenerationAI.generateSubtitles(
            videoUrl,
            language || 'English',
            languageCode || 'en'
        );

        // Convert to requested format (default VTT)
        const format = body.format || 'vtt';
        let subtitleContent: string;
        let subtitleUrl = '';

        if (format === 'vtt') {
            subtitleContent = subtitleGenerationAI.segmentsToVTT(subtitleTrack.segments);
        } else if (format === 'srt') {
            subtitleContent = subtitleGenerationAI.segmentsToSRT(subtitleTrack.segments);
        } else {
            return NextResponse.json(
                { error: 'Invalid format. Must be "vtt" or "srt"' },
                { status: 400 }
            );
        }

        // In production, upload subtitle file to storage (Cloudinary, S3, etc.)
        // For now, save to database
        await subtitleGenerationAI.saveSubtitles(episodeId, subtitleTrack, subtitleUrl);

        // Update episode with subtitle info
        await db.collection('anime_episodes').updateOne(
            { _id: new ObjectId(episodeId) },
            {
                $addToSet: {
                    subtitles: {
                        language: subtitleTrack.language,
                        languageCode: subtitleTrack.languageCode,
                        url: subtitleUrl,
                        format: format,
                        isAutoGenerated: true
                    }
                }
            }
        );

        return NextResponse.json({
            success: true,
            subtitle: {
                language: subtitleTrack.language,
                languageCode: subtitleTrack.languageCode,
                format: format,
                url: subtitleUrl,
                content: subtitleContent,
                isAutoGenerated: true,
                segmentCount: subtitleTrack.segments.length
            },
            message: 'Subtitles generated successfully'
        });
    } catch (error: any) {
        console.error('Subtitle generation error:', error);
        return NextResponse.json(
            { error: 'Failed to generate subtitles', details: error.message },
            { status: 500 }
        );
    }
}

// Get subtitles for an episode
export async function GET(request: NextRequest) {
    try {
        const { searchParams } = new URL(request.url);
        const episodeId = searchParams.get('episodeId');
        const languageCode = searchParams.get('languageCode');

        if (!episodeId) {
            return NextResponse.json(
                { error: 'Episode ID is required' },
                { status: 400 }
            );
        }

        const client = await clientPromise;
        const db = client.db('mangawebsite');

        const query: any = { episodeId };
        if (languageCode) {
            query.languageCode = languageCode;
        }

        const subtitles = await db.collection('anime_subtitles')
            .find(query)
            .sort({ createdAt: -1 })
            .toArray();

        return NextResponse.json({
            subtitles: subtitles.map((sub: any) => ({
                _id: sub._id.toString(),
                episodeId: sub.episodeId,
                language: sub.language,
                languageCode: sub.languageCode,
                format: sub.format,
                url: sub.url,
                isAutoGenerated: sub.isAutoGenerated,
                createdAt: sub.createdAt
            })),
            total: subtitles.length
        });
    } catch (error: any) {
        console.error('Error fetching subtitles:', error);
        return NextResponse.json(
            { error: 'Failed to fetch subtitles', details: error.message },
            { status: 500 }
        );
    }
}

